spring:
  application:
    name: rocketmq

rocketmq:
  name-server: 192.168.42.133:9876
  producer:
    group: producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
  consumer:
    group: TestGroup
    topic: TestTopic

logging:
  file:
    name: spring.log
