#!/bin/bash

# 将文件描述符3重定向到STDOUT
exec 3>&1

# 将STDOUT重定向到文件test14out
exec 1>test14out
echo "This should store in the output file"
echo "along with this line."

# 将STDOUT重定向到文件描述符3
exec 1>&3
echo "Now things should be back to normal"
