#!/bin/bash

# 将文件描述符6重定向到STDIN
exec 6<&0
# 将STDIN重定向到一个文件
exec 0<testfile

count=1
while read line; do
    echo "Line #$count: $line"
    count=$((count + 1))
done

# 将STDIN重定向到文件描述符6
exec 0<&6
read -p "Are you done now?" answer
case $answer in
Y | y)
    echo "Goodbye"
    ;;
N | n)
    echo "Sorry,this is the end."
    ;;
esac
