spring:
  application:
    name: sentinel

  cloud:
    sentinel: # sentinel config
      transport:
        dashboard: 10.10.10.207:6789
        client-ip: 10.10.10.207
#        clientIp: 10.10.10.207
        port: 8719




  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://dev.ruoyang.com:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL123!
