server:
  port: 8080

spring:
  datasource:
    username: root
    password: mysql123456
    url: jdbc:mysql://192.168.254.133:3306/test?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      table-prefix: tb_
      id-type: auto
  mapper-locations: classpath:/mapper/**.xml

#knife4j:
#  enable: true
#  openapi:
#    title: 用户管理接口文档
#    description: "用户管理接口文档"
#    email: 123456@qq.com
#    concat: 张飞
#    url: https://www.zhangfei.com
#    version: v1.10
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.xxx.mybatisplus.controller
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xxx.mybatisplus.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
