

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.254.133:3306/big_event
    username: root
    password: mysql123456
server:
  port: 80
  servlet:
    context-path: /

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰